language: node_js
node_js:
  - "6"
  - "4"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
 - psql -c 'create database test_twitter;' -U postgres -w

 - psql -f 'testdatabasescript.sql'
